apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: {{ template "app.name" . }}-cm
data:
  config.yaml: |-
    server:
        address: 0.0.0.0:8080
        contextName: authn
        sessionTokenExpiration: 3600