
{{- if .Values.istio.enabled -}}
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: {{ .Release.Name }}-destinationrule
  namespace: {{ .Release.Namespace }}
spec:
  host: "{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
{{- end -}}
