# Default values for api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
environment: dev
image:
  repository: eu.gcr.io/mmdh-dev/istio-authn
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: http
  type: NodePort
  externalPort: 80
  internalPort: 8080
autoscaler:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
disruptionbudget:
  enabled: true
ingress:
  enabled: true
  tls: false
  basefqdn: istio-authn.lab.digitalhub.masmovil.com
  basepath: /*
  annotations:
    kubernetes.io/ingress.class: gce
    ingress.kubernetes.io/rewrite-target: /
resources:
   limits:
    cpu: 100m
    memory: 128Mi
   requests:
    cpu: 10m
    memory: 64Mi
livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 3
  timeoutSeconds: 2
  failureThreshold: 3
  successThreshold: 1
readinessProbe:
  initialDelaySeconds: 1
  periodSeconds: 2
  timeoutSeconds: 3
  failureThreshold: 3
  successThreshold: 1
app:
  local_redis: false
  datastore_emulator: false
  profiler: 
    enabled: true
  tracing:
    enabled: false
